# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-07 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item_name', models.TextField()),
                ('item_description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('person_name', models.TextField()),
                ('person_address', models.TextField()),
                ('person_phone_number', models.TextField()),
                ('person_role', models.TextField(default='MANAGER')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vendor_name', models.TextField()),
                ('vendor_phone_number', models.TextField()),
                ('vendor_address', models.TextField()),
                ('vendor_email', models.TextField()),
            ],
        ),
    ]
