# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-07 12:50
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PurchaseOrder', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('delivery_order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('shipping_instructions', models.TextField()),
                ('time_created', models.DateTimeField()),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person')),
                ('purchase_order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PurchaseOrder.PurchaseOrder')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ref_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('delivery_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeliveryOrder.DeliveryOrder')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Item')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='deliveryorderitem',
            unique_together=set([('delivery_order_id', 'item_id')]),
        ),
    ]
